
session_tz: America/New_York

# --- Signal gates ---
rvol_lookback: 20
rvol_threshold: 1.5
breakout_lookback: 24
atr_lookback: 14
atr_pct_min: 0.0008

# Trend filters
trend_ema_len: 96       # base timeframe EMA (e.g., 15m bars ~1 day)
htf_minutes: 60         # higher timeframe (60 = 1h)
htf_ema_len: 48         # HTF EMA length

# Intraday window (NY)
intraday_start_h: 0
intraday_start_m: 0
intraday_end_h: 23
intraday_end_m: 59

# --- Risk & exits ---
risk_per_trade: 0.01
sl_atr_mult: 1.5
tp_atr_mult: 3.0
use_trailing: true
trail_atr_mult: 2.0
cooldown_bars: 8
max_daily_loss_pct: 0.02   # pause after -2% day

# --- Fees & slippage ---
fee_model: maker_taker
entry_is_taker: true
exit_is_taker: true
taker_fee_pct: 0.0006
maker_rebate_pct: 0.0002
commission_pct: 0.0005
slippage_pct: 0.0008

venues:
  binance:
    taker_fee_pct: 0.0004
    maker_rebate_pct: 0.0001
    slippage_pct: 0.0007
  bybit:
    taker_fee_pct: 0.00055
    maker_rebate_pct: 0.0002
    slippage_pct: 0.0010

# --- Backtest ---
initial_equity: 10000
seed: 42
